export const tags = [
  "śniadanie",
  "obiad",
  "kolacja",
  "kurczak",
  "ryby",
  "owoce",
  "fit",
  "praca",
  "impreza",
  "przekąski",
  "wypieki",
  "napoje",
];

export const options = [
  "najnowsze",
  "najstarsze",
  "nazwa: a-z",
  "nazwa: z-a",
  "czas przygotowania: rosnąco",
  "czas przygotowania: malejąco",
];

export const avatars = [
  {
    id: 1,
    name: "kobiety",
    images: [
      "/assets/images/avatars/female/avatark1.jpg",
      "/assets/images/avatars/female/avatark2.jpg",
      "/assets/images/avatars/female/avatark3.jpg",
      "/assets/images/avatars/female/avatark4.jpg",
      "/assets/images/avatars/female/avatark5.jpg",
      "/assets/images/avatars/female/avatark6.jpg",
      "/assets/images/avatars/female/avatark7.jpg",
      "/assets/images/avatars/female/avatark8.jpg",
      "/assets/images/avatars/female/avatark9.jpg",
      "/assets/images/avatars/female/avatark10.jpg",
      "/assets/images/avatars/female/avatark11.jpg",
      "/assets/images/avatars/female/avatark12.jpg",
      "/assets/images/avatars/female/avatark13.jpg",
      "/assets/images/avatars/female/avatark14.jpg",
      "/assets/images/avatars/female/avatark15.jpg",
      "/assets/images/avatars/female/avatark16.jpg",
      "/assets/images/avatars/female/avatark17.jpg",
      "/assets/images/avatars/female/avatark18.jpg",
      "/assets/images/avatars/female/avatark19.jpg",
      "/assets/images/avatars/female/avatark20.jpg",
      "/assets/images/avatars/female/avatark21.jpg",
      "/assets/images/avatars/female/avatark22.jpg",
      "/assets/images/avatars/female/avatark23.jpg",
      "/assets/images/avatars/female/avatark24.jpg",
      "/assets/images/avatars/female/avatark25.jpg",
      "/assets/images/avatars/female/avatark26.jpg",
      "/assets/images/avatars/female/avatark27.jpg",
      "/assets/images/avatars/female/avatark28.jpg",
      "/assets/images/avatars/female/avatark29.jpg",
      "/assets/images/avatars/female/avatark30.jpg",
      "/assets/images/avatars/female/avatark31.jpg",
      "/assets/images/avatars/female/avatark32.jpg",
      "/assets/images/avatars/female/avatark33.jpg",
      "/assets/images/avatars/female/avatark34.jpg",
      "/assets/images/avatars/female/avatark35.jpg",
      "/assets/images/avatars/female/avatark36.jpg",
    ],
  },
  {
    id: 2,
    name: "mężczyźni",
    images: [
      "/assets/images/avatars/male/avatarm1.jpg",
      "/assets/images/avatars/male/avatarm2.jpg",
      "/assets/images/avatars/male/avatarm3.jpg",
      "/assets/images/avatars/male/avatarm4.jpg",
      "/assets/images/avatars/male/avatarm5.jpg",
      "/assets/images/avatars/male/avatarm6.jpg",
      "/assets/images/avatars/male/avatarm7.jpg",
      "/assets/images/avatars/male/avatarm8.jpg",
      "/assets/images/avatars/male/avatarm9.jpg",
      "/assets/images/avatars/male/avatarm10.jpg",
      "/assets/images/avatars/male/avatarm11.jpg",
      "/assets/images/avatars/male/avatarm12.jpg",
      "/assets/images/avatars/male/avatarm13.jpg",
      "/assets/images/avatars/male/avatarm14.jpg",
      "/assets/images/avatars/male/avatarm15.jpg",
      "/assets/images/avatars/male/avatarm16.jpg",
      "/assets/images/avatars/male/avatarm17.jpg",
      "/assets/images/avatars/male/avatarm18.jpg",
      "/assets/images/avatars/male/avatarm19.jpg",
      "/assets/images/avatars/male/avatarm20.jpg",
      "/assets/images/avatars/male/avatarm21.jpg",
      "/assets/images/avatars/male/avatarm22.jpg",
    ],
  },
];

export const levels = [
  "każdy to ugotuje",
  "łatwy",
  "średni",
  "trudny",
  "nie dasz rady...",
];
